export type ServiceType =
  | 'oil_change'
  | 'tire_rotation'
  | 'tire_replacement'
  | 'brake_inspection'
  | 'brake_replacement'
  | 'air_filter'
  | 'cabin_filter'
  | 'battery'
  | 'coolant_flush'
  | 'transmission_fluid'
  | 'spark_plugs'
  | 'timing_belt'
  | 'wheel_alignment'
  | 'inspection'
  | 'registration'
  | 'other';
